./main \
--template_filename_axmodel "llama3-int8/llama_l%d.axmodel" \
--axmodel_num 32 \
--tokenizer_type 2 \
--bos 0 --eos 0 \
--filename_tokenizer_model http://10.126.33.167:12345 \
--filename_post_axmodel llama3-int8/llama_post.axmodel \
--filename_tokens_embed llama3-int8/model.embed_tokens.weight.bfloat16.bin \
--tokens_embed_num 128256 \
--tokens_embed_size 4096 \
--live_print 1 \
--continue 1 \
--prompt "$1"
